### PR TITLE
switch dockerhub organization to lfncnti

### PR DESCRIPTION
**Pull request by martin-mat**
Switch organization to lfncnti and bump
cluster-tools image version to v1.0.6.

Refs: cnti-testcatalog/testsuite#2063

### CODE REVIEW

**Comment by martin-mat** [comment]
tested here:
https://github.com/cnti-testcatalog/testsuite/actions/runs/10452643034

**Review by horecoli — APPROVED** [review]
good to have it, finally👍

**Review by kosstennbl — APPROVED** [review]
LGTM

**Review by Smitholi67 — APPROVED** [review]
lgtm

**Review by rich-l — APPROVED** [review]
lgtm

**Pull request merged**
